# Application properties
server:
  port: 8010

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sims
    username: test
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update